# Generated by Django 5.1 on 2024-12-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_unique_service_within_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='unique_service_within_category',
        ),
    ]
