# Generated by Django 5.1 on 2024-12-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_unique_service_within_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
