# Generated by Django 5.1 on 2025-01-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
