# Generated by Django 5.1 on 2025-01-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
