# Generated by Django 5.1 on 2025-01-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
