# Generated by Django 5.1 on 2025-01-23 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_workschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
