# Generated by Django 5.1 on 2025-01-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_workschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
