# Generated by Django 5.1 on 2025-01-24 08:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_workschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='leave_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, help_text='List of leave days when no appointments can be scheduled.', size=None),
        ),
    ]
