# Generated by Django 5.1 on 2025-01-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_workschedule_leave_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='leave_days',
        ),
        migrations.CreateModel(
            name='LeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of leave when no appointments can be scheduled.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_days', to='services.employee')),
            ],
            options={
                'ordering': ['employee', 'date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
