# Generated by Django 5.1 on 2025-01-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_workschedule_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['employee', 'day_of_week', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together=set(),
        ),
    ]
