# Generated by Django 5.1 on 2025-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='day_of_week',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=10),
        ),
    ]
