# Generated by Django 5.1 on 2025-01-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_workschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['employee', 'day_of_week']},
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
